# Generated by Django 3.2.13 on 2023-10-01 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mclass', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
