# Generated by Django 3.2.13 on 2023-10-02 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mclass', '0004_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=400)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image', models.URLField(blank=True, default='')),
                ('private', models.BooleanField(default=False)),
                ('category', models.CharField(max_length=30)),
                ('closed', models.BooleanField(default=False)),
                ('student', models.ManyToManyField(related_name='sclass', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tclass', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
