# Generated by Django 3.2.13 on 2023-12-07 18:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mclass', '0006_classroom_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='image',
            field=models.URLField(blank=True, default='https://img.freepik.com/free-vector/hand-drawn-flat-design-stack-books-illustration_23-2149341898.jpg', null=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='request',
            field=models.ManyToManyField(blank=True, related_name='request', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='student',
            field=models.ManyToManyField(blank=True, related_name='sclass', to=settings.AUTH_USER_MODEL),
        ),
    ]
