# Generated by Django 5.0 on 2023-12-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mclass', '0008_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
